# Task 1 Date Feature Engineering

Create new date-related columns from the transaction_date column.

In [6]:
import pandas as pd
df = pd.read_csv('../data/q3_retail_promotions.csv')

df.head()

,transaction_date,store_id,store_size,location_type,promotion_type,is_weekend,is_festival,competition_density,items_sold
0,2022-01-01,28,small,semi-urban,free_gift,1,0,5,224
1,2022-01-01,5,medium,semi-urban,free_gift,1,1,1,348
2,2022-01-02,13,small,semi-urban,loyalty_points,1,0,6,249
3,2022-01-02,17,small,urban,free_gift,1,0,7,259
4,2022-01-03,50,medium,semi-urban,bogo,0,0,3,277

checked the first few rows.

In [7]:
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

converted the transaction_date column into date format.

This is important because we need to extract year, month, and day information from it.

In [8]:
df['year'] = df['transaction_date'].dt.year
df['month'] = df['transaction_date'].dt.month
df['day_of_week'] = df['transaction_date'].dt.dayofweek

The day_of_week column gives the day as a number:

- 0 = Monday
- 1 = Tuesday
- 2 = Wednesday
- 3 = Thursday
- 4 = Friday
- 5 = Saturday
- 6 = Sunday

In [9]:
df['is_month_end'] = 0
df.loc[df['transaction_date'].dt.day >= 25, 'is_month_end'] = 1

created a new column called is_month_end.

If the day of the month is 25 or more, I set it to 1.
Otherwise, I set it to 0.

In [10]:

df[['transaction_date', 'year', 'month', 'day_of_week', 'is_month_end']].head()

  transaction_date  year  month  day_of_week  is_month_end
0       2022-01-01  2022      1            5             0
1       2022-01-01  2022      1            5             0
2       2022-01-02  2022      1            6             0
3       2022-01-02  2022      1            6             0
4       2022-01-03  2022      1            0             0

The output shows the new columns created from the transaction_date column.

- year = year
- month = month
- day_of_week = day number
- is_month_end = 0 because date is before 25

This means the feature engineering is correct.